### ISSUE TITLE
Error Handling With Metadata Will throw TypeError

### ISSUE THREAD

**Issue by HsinHeng** [malijs/mali#254] opened 2021-05-15 10:05 UTC
**Describe the bug**
I follow the reference from https://mali.js.org/guide/errors.html#custom-errors,
When I was add metadata to my custom error Error/GRPCError or others recommend error utilts,
It will throw follow error:

../node_modules/@grpc/grpc-js/build/src/server-call.js:379
                }, statusObj.metadata.toHttp2Headers());
                                      ^

TypeError: statusObj.metadata.toHttp2Headers is not a function
    at ServerHttp2Stream.<anonymous> (../node_modules/@grpc/grpc-js/build/src/server-call.js:379:39)
    at Object.onceWrapper (events.js:482:28)
    at ServerHttp2Stream.emit (events.js:376:20)
    at Http2Stream.onStreamTrailers (internal/http2/core.js:395:15)

**To Reproduce**

**Expected behavior**
Server will send metadata to client.

**Environment**
 - Version: @grpc/grpc-js": "^1.2.12,  "mali": "^0.41.2"
 - Node.js version: 14.17, 10.13
 - OS: MAC OS

**Comment by anonrig** [comment] 2021-05-15 17:00
Hi! Can you provide an example code for us to reproduce?

**Comment by HsinHeng** [comment] 2021-05-16 04:22
> Hi! Can you provide an example code for us to reproduce?

server-side code
```
const grpc = require("grpc");

module.exports = async function (ctx, next) {
	try {
		throw new Error("error!");
	} catch (error) {
		error.code = grpc.status.PERMISSION_DENIED;
		error.metadata = new grpc.Metadata();
		error.metadata.add('type', 'AUTH');
		error.metadata.add('code', '5000');
		error.metadata.add('status', 'INVALID_TOKEN');

		throw error;
	}
};

server-side error:
Error: error!
    at module.exports (_WORKSPACE_/server/grpc/implements/health/get-health/handler/index.js:5:9)
    at dispatch (_WORKSPACE_/node_modules/@malijs/compose/index.js:48:32)
    at _WORKSPACE_/node_modules/grpc-lib/middlewares/logger.js:7:9
    at dispatch (_WORKSPACE_/node_modules/@malijs/compose/index.js:48:32)
    at _WORKSPACE_/node_modules/@malijs/compose/index.js:40:12
    at execRes (_WORKSPACE_/node_modules/mali/lib/run.js:31:3)
    at exec (_WORKSPACE_/node_modules/mali/lib/run.js:85:12)
    at Object.getLotteries (_WORKSPACE_/node_modules/mali/lib/app.js:304:14)
    at handleUnary (_WORKSPACE_/node_modules/@grpc/grpc-js/build/src/server.js:451:13) {
  code: 7,
  metadata: Metadata {
    _internal_repr: { type: [Array], code: [Array], status: [Array] },
    flags: 0
  }
}
_WORKSPACE_/node_modules/@grpc/grpc-js/build/src/server-call.js:379
                }, statusObj.metadata.toHttp2Headers());
                                      ^

TypeError: statusObj.metadata.toHttp2Headers is not a function
    at ServerHttp2Stream.<anonymous> (_WORKSPACE_/node_modules/@grpc/grpc-js/build/src/server-call.js:379:39)
    at Object.onceWrapper (events.js:482:28)
    at ServerHttp2Stream.emit (events.js:376:20)
    at Http2Stream.onStreamTrailers (internal/http2/core.js:395:15)



```

client-side code
```

const call = healthClient.getHealth({}, metadata, (error, res) => {
            if (error) {
                    console.log(error);
            } else {
                    console.log(res.message);
            }
});
```

client-side throw error:

Metadata {
  internalRepr: Map(2) {
    'content-type' => [ 'application/grpc+proto' ],
    'date' => [ 'Sun, 16 May 2021 04:11:57 GMT' ]
  },
  options: {}
}
Error: 14 UNAVAILABLE: Connection dropped
    at Object.callErrorFromStatus (_WORKSPACE_/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (_WORKSPACE_/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
    at Object.onReceiveStatus (_WORKSPACE_/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (_WORKSPACE_/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at _WORKSPACE_/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  code: 14,
  details: 'Connection dropped',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}

**Comment by anonrig** [comment] 2021-05-16 09:23
I couldn't reproduce your case with the following code. Can you provide a working example that reproduces the error you've stated?

```javascript
import Mali from 'mali'
import path from 'path'
import grpc from '@grpc/grpc-js'
const app = new Mali(path.join(path.resolve('.'), './service.proto'))

function GetWidget(ctx) {
  const err = new Error('Not Authorized')
  err.code = grpc.status.PERMISSION_DENIED
  err.metadata = new grpc.Metadata()
  err.metadata.add('type', 'AUTH')
  err.metadata.add('code', '5000')
  err.metadata.add('status', 'INVALID_TOKEN')
  throw err
  ctx.res = { name: 'testing' }
}

app.use({ GetWidget })

await app.start('127.0.0.1:50051')
```

and with proto definition

```
syntax = "proto3";

package ErrorExample;

service SampleService {
  rpc GetWidget (WidgetRequest) returns (Widget) {}
}

message Widget {
  string name = 1;
}

message WidgetRequest {
  int32 id = 1;
}
```

and using the dependencies as you said:

```
{
  "name": "mali-exampl",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@grpc/grpc-js": "^1.2.12",
    "@grpc/proto-loader": "^0.6.2",
    "mali": "^0.41.2"
  }
}
```

**Comment by HsinHeng** [comment] 2021-05-16 11:32
> ```js
> import grpc from '@grpc/grpc-js'
> ```

I got the point, I used the

```
const grpc = require("grpc");
```

will throw my case error.

what is diffrence between @grpc/grpc-js & grpc lib?



However I use @grpc/grpc-js & GRPCError recommend lib, I got the same error,
```
const grpc = require("@grpc/grpc-js");
const GRPCError = require("grpc-error");

function GetWidget(ctx) {
  const metadata = new grpc.Metadata()

  metadata.add('type', 'AUTH')
  metadata.add('code', '5000')
  metadata.add('status', 'INVALID_TOKEN');

  throw new GRPCError('Not Authorized', grpc.status.PERMISSION_DENIED, metadata);
  ctx.res = { name: 'testing' }
}
```

**Comment by anonrig** [comment] 2021-05-16 12:22
Ah! grpc-error was last updated 4 years ago which directly depends on grpc-create-error package which was last updated 4 months ago. The main difference between the grpc and the @grpc/grpc-js package is, grpc-js package is rewritten in JavaScript, but the old `grpc` package is just a library that creates a binding using the C node bindings.

We are a direct dependant of `@grpc/grpc-js` since it will be the default one in the future, and doesn't require any build process for C bindings.

The `import` and `require` cases depend on whether your project is ESM-based or CommonJS based.

I suggest directly using `@grpc/grpc-js` package and create your own errors using the following code:

```javascript
const grpc = require('@grpc/grpc-js')
const error = new Error('Hello world')
error.code = grpc.status.NOT_FOUND
error.metadata = new Metadata()
throw error
```

Since this is not a bug, but a documentation-related issue, I'm going to close it. Thank you for contacting us!

**Closed by anonrig** 2021-05-16 12:22 UTC
Labels: bug, invalid

**Comment by HsinHeng** [comment] 2021-05-16 14:39
> Ah! grpc-error was last updated 4 years ago which directly depends on grpc-create-error package which was last updated 4 months ago. The main difference between the grpc and the @grpc/grpc-js package is, grpc-js package is rewritten in JavaScript, but the old `grpc` package is just a library that creates a binding using the C node bindings.
> 
> We are a direct dependant of `@grpc/grpc-js` since it will be the default one in the future, and doesn't require any build process for C bindings.
> 
> The `import` and `require` cases depend on whether your project is ESM-based or CommonJS based.
> 
> I suggest directly using `@grpc/grpc-js` package and create your own errors using the following code:
> 
> ```js
> const grpc = require('@grpc/grpc-js')
> const error = new Error('Hello world')
> error.code = grpc.status.NOT_FOUND
> error.metadata = new Metadata()
> throw error
> ```
> 
> Since this is not a bug, but a documentation-related issue, I'm going to close it. Thank you for contacting us!

OK, Thank for your kindly help. ^^
